"""Chirality from the arrow: the computational half.

The claim to be tested is that reversing a traversal exchanges the two spinor
orientations. If that holds, then the corpus's proved arrow results decide which
orientation is readable, and chirality becomes a property of the traversal direction
rather than a property of a representation.

Four checks:
  1. Negation maps the spinor sector to itself as a set but exchanges the two
     W(A3)-orbits of the family index. Reversal therefore swaps 4 and 4bar.
  2. The same holds on the D5 side: negation exchanges the 16 and the 16bar.
  3. A forward cycle composed with its own reverse has zero net displacement and
     therefore writes no record. This is the configuration a Dirac mass term needs.
  4. The Distler-Garibaldi configuration is not instantiated: the decay group is
     finite, so there is no SL(2,C) whose centralizer is the gauge group.
"""
import itertools, json, os, datetime
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
R = []
for i, j in itertools.combinations(range(8), 2):
    for si, sj in itertools.product((2, -2), repeat=2):
        v = [0]*8; v[i] = si; v[j] = sj
        R.append(tuple(v))
for s in itertools.product((1, -1), repeat=8):
    if s.count(-1) % 2 == 0:
        R.append(tuple(s))
R = np.array(sorted(set(R)), dtype=np.int64)
G = (R @ R.T) // 4
idx = {tuple(v): i for i, v in enumerate(R.tolist())}
neg = np.array([idx[tuple((-R[i]).tolist())] for i in range(240)])

# the A3 of T31
A3 = None
for a, b, c in itertools.combinations(range(240), 3):
    if G[a,b] == -1 and G[b,c] == -1 and G[a,c] == 0 and np.linalg.matrix_rank(R[[a,b,c]]) == 3:
        A3 = [a, b, c]; break
S = R[A3].astype(float)/2.0
span = S.T @ np.linalg.pinv(S @ S.T) @ S
perp = np.eye(8) - span

def refl(a):
    a = a/np.linalg.norm(a); return np.eye(8) - 2*np.outer(a, a)
W, frontier = [np.eye(8)], [np.eye(8)]
while frontier:
    nxt = []
    for g in frontier:
        for s in [refl(R[i].astype(float)/2.0) for i in A3]:
            h = s @ g
            if not any(np.allclose(h, k) for k in W): W.append(h); nxt.append(h)
    frontier = nxt

spinor = [i for i in range(240)
          if abs(float(R[i]/2.0 @ span @ (R[i]/2.0)) - 0.75) < 1e-9]
vector = [i for i in range(240)
          if abs(float(R[i]/2.0 @ span @ (R[i]/2.0)) - 1.0) < 1e-9]

# --- family-index orbits, as in families.py ---------------------------------------
wts = []
for i in spinor:
    w = span @ (R[i].astype(float)/2.0)
    if not any(np.allclose(w, v) for v in wts): wts.append(w)
wts = np.array(wts)
orb, seen = [], set()
for k in range(len(wts)):
    if k in seen: continue
    o = set()
    for g in W:
        im = g @ wts[k]
        for m in range(len(wts)):
            if np.allclose(im, wts[m]): o.add(m)
    seen |= o; orb.append(sorted(o))
which = {m: n for n, o in enumerate(orb) for m in o}
def wt_index(i):
    w = span @ (R[i].astype(float)/2.0)
    for m in range(len(wts)):
        if np.allclose(w, wts[m]): return m
    return None

# CHECK 1: negation maps the spinor sector to itself, exchanging the two orbits
in_sector = all(neg[i] in spinor for i in spinor)
swaps = [which[wt_index(neg[i])] != which[wt_index(i)] for i in spinor]
check1 = in_sector and all(swaps)

# CHECK 2: on the D5 side, negation reverses the spinor weight
d5_reversed = all(np.allclose(perp @ (R[neg[i]].astype(float)/2.0),
                              -(perp @ (R[i].astype(float)/2.0))) for i in spinor)

# CHECK 3: a cycle composed with its reverse writes nothing
rng = np.random.default_rng(0)
loop = [spinor[k] for k in rng.choice(len(spinor), 12, replace=False)]
fwd = sum(R[i] for i in loop)
net = fwd + sum(R[neg[i]] for i in reversed(loop))
check3 = bool(np.all(net == 0))

# CHECK 4: the decay group is finite, so no SL(2,C) is present
# The DG configuration needs a connected SL(2,C) subgroup whose centralizer is the
# gauge group. Here the decay is generated by three reflections and closes at order 24.
decay_is_finite = len(W) == 24
# its centralizer in the root system is the A3 + D5 pair, with no continuous factor
# acting on the geometry block as SL(2,C): the block is fixed pointwise by W.
fixed_dim = int(round(sum(abs(e - 1) < 1e-9 for e in np.linalg.eigvalsh(sum(W)/len(W)))))
check4 = decay_is_finite and fixed_dim == 5

# --- the 3+2 versus 4+1 question ---------------------------------------------------
# D18 partitions the surviving block 4+1 on the criterion "enters the quadratic form".
# The gauge stabiliser needs 3+2 on the criterion "freely traversable in both
# directions". These are different criteria on the same five directions, and both are
# stated by the corpus: T15 makes the clock monotone, D18 excludes closure from
# traversable directions. So exactly three of the five are freely reversible.
partitions = {
    "metric criterion (D18): what enters P_X - P_T":       [4, 1],
    "reversibility criterion (T15, D18): freely traversable": [3, 2],
}

print("CHECK 1  negation keeps the spinor sector and exchanges the family orbits")
print(f"           stays in sector: {in_sector}    exchanges 4 <-> 4bar: {all(swaps)}")
print("CHECK 2  negation reverses the D5 spinor weight, exchanging 16 and 16bar")
print(f"           {d5_reversed}")
print("CHECK 3  a cycle composed with its reverse has zero net displacement")
print(f"           {check3}   (this is the configuration a Dirac mass needs)")
print("CHECK 4  the Distler-Garibaldi configuration is not instantiated")
print(f"           decay group finite, order {len(W)}: {decay_is_finite}")
print(f"           it fixes the geometry block pointwise, dim {fixed_dim}: {fixed_dim==5}")
print(f"           therefore no connected SL(2,C) whose centralizer is the gauge group")
print()
print("The two partitions of the surviving five, on two different criteria:")
for k, v in partitions.items():
    print(f"   {v[0]} + {v[1]}   {k}")
print()
print(f"spinor-sector roots {len(spinor)}, vector-sector roots {len(vector)}")

json.dump({"generated": datetime.datetime.now().isoformat(timespec="seconds"),
           "negation_preserves_spinor_sector": bool(in_sector),
           "negation_exchanges_family_orbits": bool(all(swaps)),
           "negation_reverses_D5_spinor_weight": bool(d5_reversed),
           "reverse_cycle_writes_nothing": check3,
           "decay_group_order": len(W),
           "decay_fixes_block_pointwise_dim": fixed_dim,
           "DG_ToE1_instantiated": False,
           "DG_reason": "no connected SL(2,C) subgroup; the decay group is finite of order 24 "
                        "and the gauge algebra is the centralizer of that finite group, not of an SL(2,C)",
           "partitions_of_the_surviving_five": partitions},
          open(os.path.join(HERE, "chirality_certificate.json"), "w"), indent=2)
