"""O1: is the admissible reduction forced to be an average over a reflection subgroup?

Paper 21 left this as the single load-bearing reading, with four results conditional on
it. The argument below closes it from A6 and D14 together, and the one step that is a
fact about E8 rather than a general theorem is checked here exhaustively.

The chain:

  1. A6 gives unital, idempotent, completely positive and bimodular. By Tomiyama's
     theorem a norm-one projection onto a subalgebra is exactly a conditional
     expectation, so C is one. No choice has been made yet.

  2. The decayed part is a history-space. D14 says the primitive crossings are the
     roots, and a carrier history is a sequence of primitive crossings. A subspace
     containing no root contains no primitive crossing, hosts no history, and so is
     not a part of the carrier that can have decayed; it is a set of directions that
     were never traversed. This is the same argument T10 already uses in Paper 21 to
     exclude A1+A1+A1. So the decayed subspace is spanned by the roots inside it.

  3. The roots lying in any subspace form a root subsystem. Checked below.

  4. The reflection group W(S) of that subsystem fixes the orthogonal complement
     pointwise, so the complement is contained in the W(S)-fixed space.

  5. Averaging over W(S) is a conditional expectation whose fixed space is exactly
     that complement.

  6. A6's covariance clause requires C to commute with the relabelling by equivalent
     carrier descriptions. For a finite group, the covariant conditional expectation
     onto the fixed algebra is unique and is the group average.

  Therefore C is averaging over W(S), which is what O1 asked for.

WHAT THIS DOES AND DOES NOT ACHIEVE. Step 2 is not free and must not be presented as
if it were. Rank-three primitive sublattices of E8 containing no root at all exist in
abundance: sampling rank-three spans of norm-four lattice vectors, roughly four in five
contain no root. So "the decayed sublattice is generated by roots" is a genuine
condition on the reduction, not an automatic property of the carrier.

O1 is therefore REDUCED rather than closed. It moves from an open question about what
kind of map C is, to a single finite condition on which sublattice decays. Given that
condition, C is forced. D14 argues strongly for the condition, since a subspace holding
no primitive crossing hosts no history and so has nothing in it that could have decayed,
but the argument is a reading of D14 and is recorded as one.

Step 3 is the only step specific to E8 and it is verified exhaustively for the rank
that matters.
"""
import itertools, json, os, datetime
import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
def _cert(n): return os.path.join(_ROOT, "certificates", n)

R = []
for i, j in itertools.combinations(range(8), 2):
    for si, sj in itertools.product((2, -2), repeat=2):
        v = [0]*8; v[i] = si; v[j] = sj
        R.append(tuple(v))
for s in itertools.product((1, -1), repeat=8):
    if s.count(-1) % 2 == 0:
        R.append(tuple(s))
R = np.array(sorted(set(R)), dtype=np.int64)
G = (R @ R.T) // 4
index = {tuple(v): i for i, v in enumerate(R.tolist())}

def roots_in_span(basis):
    B = R[basis].astype(float)
    P = B.T @ np.linalg.pinv(B @ B.T) @ B
    return [i for i in range(240)
            if abs(R[i].astype(float) @ P.T - R[i].astype(float)).max() < 1e-8]

def is_subsystem(S):
    """Closed under its own reflections, and closed under negation."""
    Sset = set(S)
    for a in S:
        if index[tuple((-R[a]).tolist())] not in Sset: return False
        for b in S:
            # s_a(b) = b - <b,a> a, with roots of norm two
            img = R[b] - G[b, a] * R[a]
            k = index.get(tuple(img.tolist()))
            if k is None or k not in Sset: return False
    return True

# --- step 3, exhaustive over every rank-three span, complete by Weyl transitivity ---
seen, checked, failures = set(), 0, []
for j, k in itertools.combinations(range(1, 240), 2):
    tri = [0, j, k]
    if np.linalg.matrix_rank(R[tri]) != 3: continue
    S = tuple(roots_in_span(tri))
    if S in seen: continue
    seen.add(S); checked += 1
    if not is_subsystem(list(S)): failures.append(S)

print("Step 3, the only step specific to E8:")
print(f"   distinct rank-three root spans examined : {checked}")
print(f"   all of them form root subsystems        : {not failures}")
print("   (complete up to conjugacy: W(E8) is transitive on the 240 roots)")

# --- step 4, on the survivor Paper 21 forced -------------------------------------
A3 = None
for a, b, c in itertools.combinations(range(240), 3):
    if G[a,b] == -1 and G[b,c] == -1 and G[a,c] == 0 and np.linalg.matrix_rank(R[[a,b,c]]) == 3:
        A3 = [a, b, c]; break
S = R[A3].astype(float)/2.0
span = S.T @ np.linalg.pinv(S @ S.T) @ S
def refl(a):
    a = a/np.linalg.norm(a); return np.eye(8) - 2*np.outer(a, a)
W, frontier = [np.eye(8)], [np.eye(8)]
while frontier:
    nxt = []
    for g in frontier:
        for s in [refl(R[i].astype(float)/2.0) for i in A3]:
            h = s @ g
            if not any(np.allclose(h, k) for k in W): W.append(h); nxt.append(h)
    frontier = nxt
C = sum(W)/len(W)
perp = np.eye(8) - span
fixes_complement = all(np.allclose(g @ perp, perp) for g in W)
avg_fixed_is_complement = np.allclose(C, perp)

print()
print("Step 4 and 5, on the A3 that Paper 21 forced:")
print(f"   |W(A3)| = {len(W)}")
print(f"   W(A3) fixes the orthogonal complement pointwise : {fixes_complement}")
print(f"   the average over W(A3) IS the projector onto it : {avg_fixed_is_complement}")
print(f"   decayed subspace is spanned by its own roots    : "
      f"{np.linalg.matrix_rank(R[roots_in_span(A3)]) == 3}")

ok = (not failures) and fixes_complement and avg_fixed_is_complement
print()
print(f"O1 chain verified where it is checkable: {ok}")
print("Steps 1 and 6 are standard results, cited rather than recomputed:")
print("   Tomiyama, on norm-one projections being conditional expectations;")
print("   uniqueness of the covariant conditional expectation onto a finite-group")
print("   fixed algebra, which is the group average.")

json.dump({"generated": datetime.datetime.now().isoformat(timespec="seconds"),
           "rank3_spans_examined": checked,
           "all_spans_are_root_subsystems": not failures,
           "failures": [list(f) for f in failures],
           "W_A3_order": len(W),
           "W_fixes_orthogonal_complement_pointwise": bool(fixes_complement),
           "group_average_equals_projector_onto_complement": bool(avg_fixed_is_complement),
           "chain_verified_where_checkable": bool(ok),
           "cited_steps": ["Tomiyama: norm-one projection onto a subalgebra is a conditional expectation",
                           "uniqueness of the covariant conditional expectation onto a finite-group fixed algebra"]},
          open(_cert("o1_closure_certificate.json"), "w"), indent=2)
