"""O2: attack the claim that the surviving spatial modes number three.

The arithmetic first. D18 makes the geometry block P_X + P_T + P_I, mutually orthogonal.
T15 proves the clock mode is single and T16 proves the closure mode is single, so
rank P_T = rank P_I = 1. Therefore

    rank P_X = 3   <=>   the surviving geometry block has dimension 5.

The carrier has rank 8 (T8). A reduction that averages over a reflection subgroup H
leaves the H-fixed subspace, whose dimension is 8 minus the rank of the root subsystem
generated by H. So

    surviving block has dimension 5   <=>   the decayed subsystem has rank 3.

That is a finite question about E8 and it is enumerated here exhaustively. W(E8) acts
transitively on the 240 roots, so every rank-3 root subsystem is Weyl-conjugate to one
containing any fixed root. Enumerating all triples containing a single fixed root is
therefore a complete enumeration up to conjugacy.

For each rank-3 subsystem S we compute its orthogonal complement subsystem S-perp and
ask which pairings put a rank-5 system on the surviving side.
"""

import os as _os
_HERE = _os.path.dirname(_os.path.abspath(__file__))
_ROOT = _os.path.dirname(_HERE)
def _cert(n): return _os.path.join(_ROOT, "certificates", n)
def _csv(n):  return _os.path.join(_ROOT, n)
import itertools, json, os, datetime, platform
import numpy as np



HERE = os.path.dirname(os.path.abspath(__file__))

# ---------------- the 240 roots, in units of 1/2 so arithmetic stays exact ---------
R = []
for i, j in itertools.combinations(range(8), 2):
    for si, sj in itertools.product((2, -2), repeat=2):
        v = [0] * 8; v[i] = si; v[j] = sj
        R.append(tuple(v))
for s in itertools.product((1, -1), repeat=8):
    if s.count(-1) % 2 == 0:
        R.append(tuple(s))
R = np.array(sorted(set(R)), dtype=np.int64)
assert R.shape == (240, 8)
G = (R @ R.T) // 4                       # exact integer Gram matrix; diagonal is 2
assert np.all(np.diag(G) == 2)

# ---------------- name a simply-laced root system from (rank, size) ----------------
def irreducible_name(rank, size):
    if size == rank * (rank + 1):                 return f"A{rank}"
    if rank >= 4 and size == 2 * rank * (rank - 1): return f"D{rank}"
    return {(6, 72): "E6", (7, 126): "E7", (8, 240): "E8"}.get((rank, size))

def classify(idx):
    """Decompose a set of root indices into orthogonal irreducible components."""
    idx = sorted(idx)
    if not idx: return "0", 0
    pos = {v: k for k, v in enumerate(idx)}
    # connected components under non-orthogonality
    seen, comps = set(), []
    for v in idx:
        if v in seen: continue
        stack, comp = [v], []
        seen.add(v)
        while stack:
            a = stack.pop(); comp.append(a)
            for b in idx:
                if b not in seen and G[a, b] != 0:
                    seen.add(b); stack.append(b)
        comps.append(comp)
    names = []
    for c in comps:
        rk = np.linalg.matrix_rank(R[c])
        nm = irreducible_name(rk, len(c)) or f"?rank{rk}n{len(c)}"
        names.append((rk, nm))
    names.sort(key=lambda t: (-t[0], t[1]))
    total = int(np.linalg.matrix_rank(R[idx]))
    return "+".join(n for _, n in names), total

def roots_in_span(basis_idx):
    """Every root lying in the linear span of the given roots."""
    B = R[basis_idx].astype(float)
    P = B.T @ np.linalg.pinv(B @ B.T) @ B          # orthogonal projector onto the span
    res = np.abs(R.astype(float) @ P.T - R.astype(float)).max(axis=1)
    return np.where(res < 1e-8)[0]

def perp_roots(basis_idx):
    """Every root orthogonal to all of the given roots."""
    return np.where((G[np.ix_(np.arange(240), basis_idx)] == 0).all(axis=1))[0]

# ---------------- exhaustive enumeration up to Weyl conjugacy ----------------------
FIXED = 0                                   # W(E8) is transitive on roots
found = {}
for j, k in itertools.combinations(range(1, 240), 2):
    tri = [FIXED, j, k]
    if np.linalg.matrix_rank(R[tri]) != 3:
        continue
    S = tuple(sorted(roots_in_span(tri)))
    if S in found: continue
    P = tuple(sorted(perp_roots(list(S))))
    sname, srank = classify(S)
    pname, prank = classify(P)
    found[S] = (sname, srank, len(S), pname, prank, len(P))

# collapse to distinct (decayed type, surviving type) pairings
pairs = {}
for v in found.values():
    key = (v[0], v[3])
    pairs.setdefault(key, {"decayed": v[0], "decayed_rank": v[1], "decayed_roots": v[2],
                           "surviving": v[3], "surviving_rank": v[4],
                           "surviving_roots": v[5], "instances": 0})
    pairs[key]["instances"] += 1

rows = sorted(pairs.values(), key=lambda d: (-d["surviving_rank"], d["decayed"]))

print(f"rank-3 root subsystems of E8, up to Weyl conjugacy: {len(pairs)} types")
print(f"(enumerated over all {len(found)} distinct rank-3 spans through one fixed root)")
print()
print(f"{'decayed':<12} {'rk':>3} {'roots':>6}   {'surviving (perp)':<12} {'rk':>3} {'roots':>6}")
print("-" * 62)
for d in rows:
    print(f"{d['decayed']:<12} {d['decayed_rank']:>3} {d['decayed_roots']:>6}   "
          f"{d['surviving']:<12} {d['surviving_rank']:>3} {d['surviving_roots']:>6}")
print()

rank5 = [d for d in rows if d["surviving_rank"] == 5]
print("Pairings leaving a rank-5 survivor, i.e. a five-dimensional geometry block:")
for d in rank5:
    print(f"  decay {d['decayed']}  ->  surviving symmetry {d['surviving']} "
          f"({d['surviving_roots']} roots)")
if not rank5:
    print("  none")

json.dump({"generated": datetime.datetime.now().isoformat(timespec="seconds"),
           "python": platform.python_version(),
           "numpy": np.__version__,
           "enumeration": "all rank-3 root subsystems of E8 up to W(E8)-conjugacy, "
                          "complete by transitivity of W on the 240 roots",
           "distinct_spans_examined": len(found),
           "pairings": rows,
           "rank5_survivors": rank5},
          open(_cert("o2_certificate.json"), "w"), indent=2)
